name: Build
on: [push]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: android-actions/setup-android@v2
      - run: ./gradlew assembleDebug -d
        working-directory: android
      - uses: actions/upload-artifact@v2
        with:
          name: Android
          path: android/app/build/outputs/apk/debug/app-debug.apk
